programmingTutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tutorialMain.urls")),
]

tutorialMain/urls.py
from django.urls import path

from . import views


app_name = 'tutorialMain'

urlpatterns = [ 
    path('', views.homeIndex, name='homeIndex'),
    path('post:<slug:slug>/<int:pk>/', views.tutorialIndex, name='singleIndex'),
]

tutorialMain/models.py
from django.db import models

# Create your models here.

from django.template.defaultfilters import slugify


class TutorialModel(models.Model):

    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, verbose_name="Slug", unique=True)
    body = models.TextField(max_length=250)
    date_of_published = models.DateField(auto_now_add=True)

    def slug(self):
        return slugify(self.title)


    def __str__(self):
        return self.title

tutorialMain/views.py
from django.shortcuts import render, get_object_or_404

from .models import TutorialModel

def homeIndex(request):
    return render(request, 'index.html', {'tutorials':TutorialModel.objects.all()})


def tutorialIndex(request, slug, pk):
    # print(slug, 'slug')
    # print(dir(TutorialModel))
    tutorial = get_object_or_404(TutorialModel, pk=pk)
    print(tutorial, tutorial.body)
    return render(request, 'single.html', {'tutorial':tutorial, 'tutorials':TutorialModel.objects.all()})

templates/base.html
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
        <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
      <a class="nav-item nav-link"  style="color:white;" href="{% url 'tutorialMain:homeIndex' %}">Home</a>
    </div>
  </div>
</nav>

 <div class="col-12" style="top: 30px;margin: 1px auto;">
          <h1 style="text-align:center;">Programming Tutorial</h1>
  </div>
<br><br>

{% block content %}

{% endblock %}

 <div class="footer">
        <p style="text-align: center;padding-top: 10px; color:white;">Made with <strike style="color: #ffffff;">❤️</strike> 🥛🥛 by
            Arsh
        </p>
    </div>


{% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script> {% endcomment %}
{% comment %} <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script> {% endcomment %}
{% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script> {% endcomment %}
        </body>
</html>

<style>

.footer {
    
    width: 100%;
    height: 50px;
    background-color: #201C29;
    bottom:0 !important;
    position: fixed;
}

.navbar-nav {
  margin: 1px auto;
}

#card {
    box-shadow: 0 0 10px rgba(0,0,0,.5);
  transition: all .5s;
}

#card:hover {
    box-shadow: 0 8px 8px rgba(0,0,0,.25);
    margin: 5px;
}

</style>

templates/index.html
{% extends "base.html" %}
{% block content %}


<div class="col col-8" style="margin:2px auto;">

<div class="jumbotron">
<div class="row" style="margin:2px auto;">
{% for tutorail in tutorials %}
  <div class="col-lx-3" style="margin:5px 5px 5px 5px;">
    <div class="card border-primary" id="card">
      <div class="card-body">
      <a href="{% url 'tutorialMain:singleIndex' tutorail.slug tutorail.pk %}"
        <h5 class="card-title">{{ tutorail.title|capfirst }}</h5>
        <p class="card-text">{{ tutorail.body|slice:":20"|safe }}</p>
        <em style="font-size:10px">{{ tutorail.date_of_published }}</em>
        </a>
      </div>
    </div>
  </div>
{% endfor %}
</div>
</div>
</div>

{% endblock %}

templates/single.html
{% extends "base.html"%}
{% block content %}

<div class="col col-sm-8" style="margin:10px auto;">
<div class="jumbotron">
<center><h4>{{ tutorial.title|capfirst }}</h4></center>
{{ tutorial.body|capfirst|safe }}<br>
<em><i>{{ tutorial.date_of_published }}</i></em>
</div>
</div>

<div class="col-md-8" style="margin:15px auto;">
<center><h5>Suggestive Tutorial</h5></center><br>
<div class="row">
<div class="container">
<div class="card-deck">
{% for tutorial in tutorials%}
  <div class="card border-primary" id="card">
    <div class="card-body text-center">
      <a href="{% url 'tutorialMain:singleIndex' tutorial.slug tutorial.pk  %}"><p class="card-text">{{ tutorial.title }}</p></a>
    </div>
  </div>
 {% endfor %} 
</div>
</div>
</div>
</div>

{% endblock %}